### ISSUE TITLE
Some instruction cycles are incorrect

### ISSUE THREAD

**Issue by chip-64bit** [twvd/snow#6]
Hello, I've found some small problems again, some instruction cycles are not correct, for the time being I've found the following instructions:

MOVEC is a illegal opcode, so it is 34 not 30.

ROM address:
1C1E: BSet.L    #$3, D0; is 12 not 10
1C38: BClr.L    #$0, D0; is 14 not 12

The above conclusions are based on this website:
https://wiki.neogeodev.org/index.php?title=68k_instructions_timings

**Comment by twvd** [comment]
Hi,

For MOVEC I'm not sure, but that's a 68020 instruction that I've only stubbed to pass the 68020 check in the Plus ROM.

However, for BSET and BCLR, my timings are correct. The timings in the NeoGeo wiki are maximums, e.g. the cycle count could be less. In your examples, the cycle count is 2 cycles shorter because the bit number tested is below 15:
https://github.com/twvd/snow/blob/acf8b5c03cbf5356e4ee3fdf1f1775de34a547ae/core/src/cpu_m68k/cpu.rs#L1665

My CPU is tested (except group 0 exceptions and MOVE.L, on my TODO list to fix..) against these tests, which are generated from the MAME 68000 core, which is based on the actual M68000 microcode: https://github.com/SingleStepTests/m68000

**Comment by chip-64bit** [comment]
> Hi,
> 
> For MOVEC I'm not sure, but that's a 68020 instruction that I've only stubbed to pass the 68020 check in the Plus ROM. I'll check the count for the illegal instruction exception.
> 
> However, for BSET and BCLR, my timings are correct. The timings in the NeoGeo wiki are maximums, e.g. the cycle count could be less. In your examples, the cycle count is 2 cycles shorter because the bit number tested is below 15:
> 
> https://github.com/twvd/snow/blob/acf8b5c03cbf5356e4ee3fdf1f1775de34a547ae/core/src/cpu_m68k/cpu.rs#L1665
> 
> My CPU is tested (except group 0 exceptions and MOVE.L, on my TODO list to fix..) against these tests, which are generated from the MAME 68000 core, which is based on the actual M68000 microcode: https://github.com/SingleStepTests/m68000

I'm sorry to say that this is what I've concluded from the Musashi comparison. Because I use Musashi in my emulator. I was fretting about the incorrect sound. It's so sad...

**Comment by twvd** [comment]
By the way, if you're writing an emulator, you may want to join the Emudev Discord :) https://discord.gg/gCsjCGyB

The #computers-misc channel is for Mac emulation

**Comment by chip-64bit** [comment]
> By the way, if you're writing an emulator, you may want to join the Emudev Discord :) https://discord.gg/gCsjCGyB
> 
> The #computers-misc channel is for Mac emulation

Thank you so much for providing this avenue! Have a nice day!
